### ISSUE TITLE
Is this working with the latest 1.5 pre-4.1 build?

### ISSUE THREAD

**Issue by ghost** [gmoeck/jasmine-sproutcore#1]
I have followed the installation process but I can't get it to work.

I have a file with:

```
describe('Jasmine', function() {
  it('makes testing JavaScript awesome!', function() {
    expect(1).toEqual(1)
  })
})
```

But in the test runner it shows me my first page of the SC app.

Here is my Buildfile:

```
require File.expand_path('../frameworks/jasmine-sproutcore/builders/jasmine_builder', __FILE__)

config :all, :required => [:"sproutcore", :"sproutcore/table", :"sproutcore/forms", :"couchdb", :"ki", :"yi"]

proxy "/janrain/get_user", :to => "localhost:8080"

namespace :build do
  desc "builds a jasmine unit test"
  build_task :test do
    Jasmine::Builder::Test.build ENTRY, DST_PATH
  end
end
```

**Comment by gmoeck** [comment]
I haven't tried it on the latest 1.5 pre. I'll give it a look today.

**Comment by gmoeck** [comment]
I was able to duplicate the problem. It seems that the main function isn't called in the 1.4 tests, but that it is in 1.5. This means that likely the main pane of your application is being appended in your tests. A work around for this is bellow, but I'm also looking into why and where this changed.

```
describe('Jasmine', function() {
  beforeEach(function() {
    YourProjectNamespace.mainPage.get('mainPane').remove();
  });

  it('makes testing JavaScript awesome!', function() {
    expect(1).toEqual(1)
  });
});
```

**Comment by gmoeck** [comment]
So the issue on this was with the amber refactor. I checked with wycats, who said it was a mistake, and submitted a pull request to patch the issue [here](https://github.com/sproutcore/sproutcore/pull/219). In the meantime the above work around should solve your problem.

**Comment by ghost** [comment]
Worked like a charm! Thanks for fast support!

**Comment by gmoeck** [comment]
The fix was pulled into master.

**Comment by ghost** [comment]
Great!
